### ISSUE TITLE
Consider disabling the cursor while in presentation mode

### ISSUE THREAD

**Issue by terlar** [positron-solutions/dslide#2] opened 2024-06-24 13:33 UTC
Now when running a presentation, I will always see my cursor at the top and it also tends to glitch out a bit, leaving a trail along the title overlay.

Setting this fixes it:
```
(setq cursor-type nil)
```

![image](https://github.com/positron-solutions/dslide/assets/280235/0573c460-4d2c-4008-a5ae-c5567edae271)

**Comment by psionic-k** [comment] 2024-06-26 00:54
Now that there is a `dslide-develop` command, I agree this makes sense as a default.  I want to add a `dslide-present` command that can create a frame if there are multiple screens and will also disable the mode line.  I almost added it already.  I just need to think about multiple screens.

For now such things can easily be done with hooks or extra commands as needed.

**Comment by psionic-k** [comment] 2024-07-03 12:05
I had a brainstorm about one of the first things we need for `dslide-present`.

The problem is when presenting, lots of time you are using some external projector or sharing a specific desktop.  You want to look at the notes while showing the audience the contents.  You need to be able to put a frame on the correct display.  This is not the kind of thing we can do with hooks because the situations change.  So, for the user, at the worst time to be interrupted, suddenly we need to use some new commands or click around manually.

So to solve this, I will use a transient interface to create a presentation frame.  It will have a UI for placing the frame.  The presentation frame and base frame will be able to swap positions.  The presentation frame will move between screens using the transient.

Finally, I will add some customization options to add arbitrary commands typically useful for this situation.

There will be separate hooks for `dslide-present`, `dslide-start`, and `dslide-develop`.  I'm not sure about whether I will restart the presentation or not.  The current interpolation only goes to root headings.

**Comment by terlar** [comment] 2024-07-03 15:21
Makes sense, perhaps it is not that given, but as you say, it depends on what the purpose of the buffer is.

I think it is fine to leave this up to the user, I currently have added this to the `dslide-start-hook` and it works well.

```elisp
(define-minor-mode hide-cursor-mode
    "Toggle hiding of the cursor."
    :lighter " Hide Cursor"
    (if hide-cursor-mode
        (setq cursor-type nil)
      (kill-local-variable 'cursor-type)))
(add-hook 'dslide-start-hook #'hide-cursor-mode)
```

**Comment by psionic-k** [comment] 2024-11-21 08:29
I added basic support for cursor hiding in 84b4b8c.  It's sort of the minimum and makes sense for out-of-the-box support.

I did a bit of work on implementing multiple frame support, but the information my Emacs could obtain through the DE backend (My Emacs used "fallback" even though I have xrandr available) was insufficient to make an implementation.

Closing this issue since it's about the cursor.

**Closed by psionic-k** 2024-11-21 08:29 UTC
